global:
  scrape_interval: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yaml"

scrape_configs:
#  - job_name: 'prometheus_metrics'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['prometheus:9090']

  - job_name: 'Node_Exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - monitoring-0:9100
          - kafka-1:9100
          - kafka-2:9100
          - kafka-3:9100


  - job_name: 'Kafka_Exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - kafka-1:9308
          - kafka-2:9308
          - kafka-3:9308






