name_server: "8.8.8.8"
vmagent_version: "latest"
victoria_metrics_version: "latest"
grafana_version: "latest"
vmalert_version: "latest"
alertmanager_version: "latest"
node_exporter_version: "latest"
node_exporter_base_image: "prom/node-exporter"
clickhouse_version: "latest"
zookeeper_version: "latest"
clickhouse_user: "username"
clickhouse_password: "password"
clickhouse_base_directory_path: "/root/"
clickhouse_test_database_name: "click"
clickhouse_test_table_name: "clicktable"
clickhouse_production_cluster_name: "PRODUCTION_CLICKHOUSE_CLUSTER"
clickhouse_keeper_base_image: "clickhouse/clickhouse-keeper"
clickhouse_keeper_version: "latest"
clickhouse_keeper_log_file_path_on_host: "/Clickhouse/Keeper/Logs/clickhouse-keeper.log"
clickhouse_keeper_log_file_path_on_container: "/var/log/clickhouse-keeper/clickhouse-keeper.log"
clickhouse_keeper_error_file_path_on_host: "/Clickhouse/Keeper/Logs/clickhouse-keeper.err.log"
clickhouse_keeper_error_file_path_on_container:  "/var/log/clickhouse-keeper/clickhouse-keeper.err.log"
clickhouse_keeper_config_path_on_host: "/Clickhouse/Keeper/Config/keeper_config.xml"
clickhouse_keeper_config_path_on_container: "/etc/clickhouse-keeper/keeper_config.xml"
clickhouse_keeper_max_con: "4096"
clickhouse_keeper_listening_address: "0.0.0.0"
clickhouse_keeper_listening_port: "2181"
clickhouse_keeper_coordination_log_storage_path_on_host: "/var/lib/clickhouse/coordination/log"
clickhouse_keeper_coordination_log_storage_path_on_container: "/var/lib/clickhouse/coordination/log"
clickhouse_keeper_coordination_snapshot_path_on_host: "/var/lib/clickhouse/coordination/snapshots"
clickhouse_keeper_coordination_snapshot_path_on_container: "/var/lib/clickhouse/coordination/snapshots"
clickhouse_keeper_raft_port: "9234"
clickhouse_base_image: "clickhouse/clickhouse-server"
clickhouse_data_path_on_host: "/Clickhouse/Data/"
clickhouse_data_path_on_container: "/var/lib/clickhouse/"
clickhouse_log_directory_path_on_host: "/Clickhouse/Logs/"
clickhouse_log_directory_path_on_container: "/var/log/clickhouse-server/"
clickhouse_log_coordination_path_on_host: "/var/log/clickhouse/coordination/logs"
clickhouse_log_coordination_path_on_container: "/var/log/clickhouse/coordination/logs"
clickhouse_snapshot_coordination_path_on_host: "/var/lib/clickhouse/coordination/snapshots"
clickhouse_snapshot_coordination_path_on_container: "/var/lib/clickhouse/coordination/snapshots"
clickhouse_log_file_path: "/var/log/clickhouse-server/clickhouse-server.log"
clickhouse_error_file_path: "/var/log/clickhouse-server/clickhouse-server.err.log"
clickhouse_metrics_exposed_on_port: "8001"
clickhouse_http_port: "8999"
clickhouse_tcp_port: "9000"
clickhouse_postgresql_port: "9005"
clickhouse_interserver_http_port: "9009"
clickhouse_listen_address: "0.0.0.0"
clickhouse_max_connections: "4096"
docker_api_version: "2.4"
clickhouse_keeper_max_log_size: "10g"
clickhouse_max_log_size: "20g"
clickhouse_memory_limit: "16g"
clickhouse_cpu_limit: "2"
clickhouse_keeper_memory_limit: "4g"
clickhouse_keeper_cpu_limit: "2"
clickhouse_log_level: "warning"
clickhouse_keeper_log_level: "trace"
clickhouse_restart_policy: "unless-stopped"
clickhouse_certs_base_path: "/Clickhouse/Config/Certs/"
clickhouse_keeper_tls_listening_port: "9281"
clickhouse_keeper_raft_port_tls: "9444"
clickhouse_cert_path_on_container: "/etc/clickhouse-server/certs/"
clickhouse_https_port: "8443"
clickhouse_tcp_secure_port: "9440"
clickhouse_interserver_https_port: "9010"
clickhouse_client_config_path_on_container: "/etc/clickhouse-client/config.xml"