---
- name: setting up Kafka cluster
  hosts: all
  become: true
  tasks:
    - name: Include variables
      include_vars: "all.yaml"

    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/pre_setup
        - $PWD/roles/docker_install

    - name: Pre Setup Kafka
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/kafka_pre_setup
      when: mode == 'kafka'


    - name: Generate Certificates For Kafka
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/kafka_cert_generation
      when: mode == 'kafka' and kafka_number == '1'


    - name: Install And Configure Kafka instances
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/kafka_install_dockerized
      when: mode == 'kafka'

    - name: Set Up Kafka Exoprter
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/kafka_install_exporter
      when: mode == 'kafka'

    - name: Set Up Kafka GUI
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/kafka_install_gui
      when: mode == 'kafka'


    - name: Deploy Node Exporter On All Nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/node_exporter_setup
      when: mode == 'monitoring'


    - name: Deploy the monitoring stack on monitoring nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/victoria_metrics_setup
      when: mode == 'monitoring'
