---
- name: check connectivity
  ping:
    data: alive



- name: Pull the kafka image
  docker_image:
    name: "{{ kafka_gui_base_image }}:{{ kafka_gui_image_version }}"
    source: pull




- name: Set the compose file for kafka GUI
  template:
    src: "templates/docker-compose-exporter.yaml.j2"
    dest: "{{ kafka_directory_base_path }}Kafka/Exporter/Docker/docker-compose.yaml"
  when: mode == 'kafka'



- name: Run the containers
  community.general.docker_compose:
    project_src: "{{ kafka_directory_base_path }}Kafka/Exporter/Docker/"
    pull: true
    recreate: never
    state: present
    restarted: false
    remove_orphans: no
    remove_volumes: false




