---
- name: check connectivity
  ping:
    data: alive


- name: install required package for generating JKS certs
  apt:
    pkg:
      - openjdk-19-jre-headless
      - openssl
    state: present


- name: Create the required directories
  file:
    path: "{{ kafka_directory_base_path }}{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0777"
  with_items:
    - Kafka
    - Kafka/Docker/
    - Kafka/Config/
    - Kafka/Config/Config
    - Kafka/Logs/
    - Kafka/Config/Certs
    - Kafka/Data/
    - Kafka/Exporter
    - Kafka/Exporter/Docker/
    - Kafka/Gui
    - Kafka/Gui/Docker/






